# valine
valine_app_id: "tdOzP65tbrubVP7AjudijgBF-gzGzoHsz"
valine_app_key: "tCMw7VUTpqIhpILQFqQH1z2d"
valine_common_place_holder: "输入你想说的内容吧~"
valine_micro_place_holder: "输入你想说的内容吧~"

# footer, html code
footer: 
  - '<a href="{{ site.baseurl }}/static/xml/rss.xml">RSS</a> | '
  - '<a href="https://github.com/Zj031210?tab=repositories">kKsk's Repositories</a>'